### ISSUE TITLE
Warning with class JavaLaunchHelper

### ISSUE THREAD

**Issue by ngbinh** [fommil/class-monkey#21]
When I try to add `-javaagent:/path/to/class-monkey-1.7.0-assembly.jar` to our JVM, this is what I get
```scala
objc[74151]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMach
ines/jdk1.8.0_60.jdk/Contents/Home/bin/java (0x100bd54c0) and /Library/Java/JavaVirtualM
achines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x100d894e0). One of
the two will be used. Which one is undefined.
```

Is it normal? Is there a way to get rid of the warning?

**Comment by fommil** [comment]
I don't think this is caused by the java agent being added, and if it is it's a very weird artefact of OS X java. Sorry I can't help further.
